[package]
name = "bad_apple_to_hltas"
version = "0.1.0"
edition = "2021"

[dependencies]
edge-detection = "0.2.6"
image = "0.24.9"
rayon = "1.10.0"
serde = {version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
vid2img = "0.1.1"
viuer = "0.7.1"
